FROM    alpine:3.15.1 AS build

WORKDIR /app

RUN     apk add --no-cache protoc

COPY    ./proto/ping.proto .

# build proto descriptor
RUN     protoc --include_imports --include_source_info \
            --descriptor_set_out=ping.pb ping.proto

FROM    envoyproxy/envoy:v1.22.0

COPY    --from=build /app/ping.pb /tmp/